module m_interface
contains
subroutine interface(ensdir,ensname,ecldir,eclname,cvar,cnum,iens,iopt)
! Provides the interface between Eclipse and EnKF file formats
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
! iopt is either one of
!   1   : Normal read of ECLIPSE.F???? and ECLIPSE.A???? restart files and
!         copies variables to ensemble(A/F)????.uf and ensembleS????.uf.
!   2   : Normal read of ensemble(A/F)????.uf and ensembleS????.uf files
!         and write of formatted ECLIPSE.F???? restart file 
!   22  : Normal read of ensemble(A/F)????.uf and ensembleS????.uf files
!         and write of formatted ECLIPSE.F???? restart file containing
!         PORO, PERMX, PERMZ, GAUSS1, GAUSS2 as time varying variables
!         for animation in floviz.
!   23  : Only reads ensemble(A/F)????.uf for extraction and printing of
!         PORO.INC, PERMX.INC, PERMZ.INC, used only to generate a reference
!         simulation from random conditioned poro-perm fields generated by
!         iniens.arch. (NOT USED ANYMORE?)
!   3   : Reads first static member in ensembleS????.uf and copies it to all
!         other members in ensemble.  This is used to create the initial 
!         static ensemble.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1


   use mod_dimensions
   use mod_fnames
   use m_ecl2ens
   use m_ens2ecl
   use m_readrft
   implicit none
   character(len=1),  intent(in) :: cvar
   character(len=4),  intent(in) :: cnum
   character(len=80), intent(in) :: eclname
   character(len=80), intent(in) :: ensname
   character(len=80), intent(in) :: ensdir
   character(len=80), intent(in) :: ecldir
   integer,           intent(in) :: iopt
   integer,           intent(in) :: iens


! Saving parameters used in interface program
   open(10,file='interface.in')
   write(10,'(a)')trim(ensdir)
   write(10,'(a)')trim(ensname)
   write(10,'(a)')trim(ecldir)
   write(10,'(a)')trim(eclname)
   write(10,'(a)')cvar
   write(10,'(a)')cnum
   write(10,'(i3.3)')iens
   write(10,'(i1)')iopt
   close(10)

   call fnames(ensdir,ensname,ecldir,eclname,cvar,cnum)
   if (iopt == 1) then 
! Copy from Eclipse restart file to ensemble file
      call ecl2ens(iens,ecldir)
!      call readrft(iens,cnum)

   elseif (iopt == 2 .or. iopt == 22 .or. iopt == 23) then
! Copy from ensemble file to Eclipse restart file
      call ens2ecl(iopt,iens,ecldir,ensdir)
     
   elseif (iopt == 3) then
! Creates static ensemble
      call ens2ecl(iopt,iens,ecldir,ensdir)

   else
      print *,'invalid iopt option: ',iopt
      return 
   endif

!   print *,'interface done.'
end subroutine
end module
