module m_sm_diagnostics
contains
subroutine sm_diagnostics()
use mod_localdefs
use mod_wellnames
use m_printhelp
use m_extractobs
use m_prodhist
use m_tecpost3D
implicit none
character(len=2) comm
character(len=100) command
character(len=80) filename
character(len=80) fname
character(len=80) dname
integer i,j,len
character(len=1) yn
logical ex

character(len=80), allocatable :: tecnames(:)
integer irepl,irepf,nrrep

integer nr,num,nrdays
character(len=4) cnum
character(len=4) ctmp(1000)
real days(1000)
real day

inquire(file='Prodhist',exist=ex)
if (.not.ex) call system('mkdir Prodhist')


inquire(file='days.dat',exist=ex)
if (ex) then
   open(10,file='days.dat')
      do i=1,1000
         read(10,'(a4,f10.2)',end=100,err=100)ctmp(i),days(i)
      enddo
   100 nrdays=i-1
   close(10)
else
   print *,'WARNING: days.dat does not exist (generated by interface ecl2ens).'
   return
endif

call wellnames()

 
comm=' '
do
   print '(a)','    ================================================================ '
   print '(a)','    =  Production history and diagnostics in Tecplot format:         '
   print '(a)','    ================================================================ '
   print '(a)','    =  h: Information about diagnostic files etc.                    '
   print '(a)','    =--------------------------------------------------------------- '
   print '(a)','    =  a: Generate Prodhist/history.dat with measurements            '
   print '(a)','    =  b: Generate Prodhist/refcaseF.dat                             '
   print '(a)','    =  c: Generate Prodhist/enkf.dat (and enks.dat)                  '
   print '(a)','    =  d: Generate production history from alternative directory     '
   print '(a)','    =--------------------------------------------------------------- '
   print '(a)','    =  t: Generate tecplot 3D diagnostic file                        '
   print '(a)','    =--------------------------------------------------------------- '
   print '(a)','    =  q: return                                                     '
   print '(a)','    ================================================================ '

   write(*,'(a)',advance='no')'Command: '
   read(*,*)comm

   select case (trim(comm))
   case('q')
      exit

   case('h')
      call printhelp('diagnostics.txt')

   case('a')
      call system('rm -f Prodhist/history.dat')
      nr=fintime-max(1,initime)
      do i=max(1,initime),fintime
         write(cnum,'(i4.4)')i
         do j=1,nrdays
            if (cnum == ctmp(j)) then
               day=days(j)
               exit
            endif
            if (j==nrdays)  print *,'day not found',cnum
         enddo
         print *,'calling extractobs with:',i,day,nr
         call extractobs(cnum,day,nr)
      enddo

   case('b')
      call prodhist(ctmp,days,nrdays,trim(refdir),'refcase')

   case('c')
      call prodhist(ctmp,days,nrdays,'Ensstat/','ensave')

   case('d')
      write(*,'(a)')'Generating production history from user selected run.'
      write(*,'(a)',advance='no')'Directory (e.g. ./Refcase/) : '
      read(*,'(a)')dname
      inquire(file=trim(dname),exist=ex)
      if (.not.ex) then
         print '(a)','Directory does not exist, try again! '
         cycle
      endif
      len=len_trim(dname)
      if (dname(len:len) /= '/') then
         print '(a)','You need to add slash to directory names: ',trim(dname)
         dname(len+1:len+1)='/'
         print '(a)','Directory name changed to: ',trim(dname)
      endif

      write(*,'(a)',advance='no')'filename  (e.g. refcase)    : '
      read(*,*)fname
      call prodhist(ctmp,days,nrdays,trim(dname),trim(fname))

   case('t')
      print '(a)','Generates 3D tecplot files for visualization.'

      write(*,'(3a)',advance='no')'Chose directory for files (e.g. ',trim(refdir),' or Ensstat/) : '
      read(*,'(a)')dname  
      inquire(file=trim(dname),exist=ex)
      if (.not.ex) then
         print '(a)','Directory does not exist, try again! '
         cycle
      endif
      len=len_trim(dname)
      if (dname(len:len) /= '/') then
         print '(a)','You need to add slash to directory names: ',trim(dname)
         dname(len+1:len+1)='/'
         print '(a)','Directory name changed to: ',trim(dname)
      endif

      write(*,'(a)')'List of files that can be processed:'
      command(:)=' '
      command='ls '//trim(dname)//'*.uf  | cut -f2 -d/ | sed  -e "s/....\.uf//"  | sort -u | sed -e "/refcaseS/d" -e "/^$/d" ' 
      call system(trim(command))

      write(*,'(a)',advance='no')'Chose filetype to process: '
      read(*,*)fname

      print '(a)','Available report steps: '
      command(:)=' '
      command='ls '//trim(dname)//trim(fname)//'*.uf  | cut -f2 -d/ '
      call system(trim(command))

      write(*,'(a)',advance='no')'Chose first report time (e.g. 3): '
      read(*,*)irepf

      write(*,'(a)',advance='no')'Chose last report time (e.g. 4) : '
      read(*,*)irepl
      if (irepl < irepf) then
         print *,'last report step is smaller than first'
         cycle
      endif

      call tecpost3D(irepf,irepl,fname,dname)
      print '(5a)','You are now ready to preplot/tecplot the file ',trim(dname),'tec',trim(fname),'.dat'


   case default
      print '(a)','Invalid command: try again!'
   end select





enddo



end subroutine
end module
